export default {
  publicTransit: {
    nav: 'Public Data', title: 'Public Transit Data', subtitle: 'Standard public model pricing, recharge ratio, group multipliers and availability monitoring.',
    backHome: 'Back home', copyDiscovery: 'Copy discovery URL', copySnapshot: 'Copy snapshot URL', disabledTitle: 'Public transit export is disabled', disabledDesc: 'An administrator needs to enable the public transit export in settings.',
    rechargeRatio: 'Recharge ratio', groups: 'Public groups', models: 'Models', generatedAt: 'Generated at', modelPricing: 'Model pricing', modelPricingHint: 'Prices are shown as $/MTok and $/request. Private account details are never exposed.',
    searchPlaceholder: 'Search group or model', allPlatforms: 'All platforms', group: 'Group', model: 'Model', multiplier: 'Multiplier', billingMode: 'Billing mode', billingToken: 'Token', billingPerRequest: 'Per request', availability: 'Availability', priceSource: 'Price source', priceSourceCustom: 'Custom', priceSourceStandard: 'Standard', priceSourceUnknown: 'Unknown',
    inputPrice: 'Input / MTok', outputPrice: 'Output / MTok', cachePrice: 'Cache', cacheInputPrice: 'Cache input / MTok', cacheCreatePrice: 'Cache create / MTok', cacheCreate: 'Cache create', cacheHit: 'Cache hit', cacheHitRate: 'Cache hit rate', totalCacheHitRate: 'Total cache hit rate', last24h: '24h', last7d: '7d', total: 'Total', perRequestPrice: 'Request / size',
    emptyModels: 'No public model pricing yet', emptyGroupModels: 'This group has no public model catalog yet', monitoring: 'Availability monitoring', monitoringHint: 'Model status, latency, availability and recent timeline.', emptyMonitoring: 'No public monitoring data yet', disclosure: 'Disclosure', upstreamType: 'Upstream type', accountPoolType: 'Account pool', cacheSupported: 'Cache pricing', completeness: 'Admission completeness', hasRechargeRatio: 'Recharge ratio', hasGroupMultipliers: 'Group multipliers', hasModelPricing: 'Model pricing', hasMonitoring: 'Availability', hasSourceDisclosure: 'Source disclosure', publicNote: 'Only public pricing, multipliers, cache and availability data are shown. Accounts, keys, cookies and internal channel IDs are never exposed.'
  }
}
